#!/bin/bash

rank=$PMI_RANK
suffix=`printf "%3.3d" $rank`
export OMP_NUM_THREADS=1

ulimit -s unlimited

#export KMP_BLOCKTIME=10000
#export KMP_LIBRARY=turnaround
#export KMP_AFFINITY="verbose,granularity=thread,scatter"
#export KMP_AFFINITY="verbose,compact"
#export KMP_MONITOR_STACKSIZE=100m
# これがないと落ちる
#export KMP_STACKSIZE=8000m
export KMP_STACKSIZE=250m

./cafemol inp/cafemol_go_1chain.inp 1> data/log.$suffix 2> data/err.$suffix
