#include "config.h"

!write_version
!> @brief Outputs version information.
subroutine write_version(lunout)

    implicit none

    integer, intent(in) :: lunout

    write (lunout, '(a)') '# Generated by CafeMol '//PROJECT_VERSION

endsubroutine write_version
